fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    java: "https://github.com/puppetlabs/puppetlabs-java"
    archive: "https://github.com/voxpupuli/puppet-archive"
    systemd: "https://github.com/voxpupuli/puppet-systemd"
